### ISSUE TITLE
IP type doesn't reach the max value

### ISSUE THREAD

**Issue by ghost** [redBorder/synthetic-producer#11]
I've found that if I set a field like this below, I never get the IP 192.168.0.102.

``` yaml
dst:
    type: ip
    min: 192.168.0.101
    max: 192.168.0.102
```

Also, if I set a field like this below, I get an error like that below:

``` yaml
dst:
    type: ip
    min: 192.168.0.101
    max: 192.168.0.101
```

Exception in thread "Thread-2" java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at net.redborder.utils.types.impl.IpType.get(IpType.java:35)
    at net.redborder.utils.generators.MessageGenerator.generate(MessageGenerator.java:31)
    at net.redborder.utils.scheduler.StandardScheduler$SenderThread.run(StandardScheduler.java:69)
