### ISSUE TITLE
set type doesn't get right the 'numbers' value

### ISSUE THREAD

**Issue by ghost** [redBorder/synthetic-producer#12]
``` yaml
  my_set:
    type: set
    numbers: 9
    components:
      http_host:
        type: constant
        value: fedoraproject.org
      market:
        type: collection
        values:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
```

This returns just eight sets. If a I set "numbers: 10", then it returns the nine sets. And, obviously, if I set "numbers: 100" it returns also nine sets.
