### ISSUE TITLE
Integer type and minimun-maximun values

### ISSUE THREAD

**Issue by ghost** [redBorder/synthetic-producer#2]
Hi all,

I've found that if I set a field like this below, I never get a 12 as value.

``` yaml
  number:
    type: integer
    min: 10
    max: 12
```

Also, if I set a field like this below, I get an error like that below:

``` yaml
  number:
    type: integer
    min: 10
    max: 10
```

Exception in thread "Thread-2" java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at net.redborder.utils.types.IntegerType.get(IntegerType.java:21)
    at net.redborder.utils.generators.MessageGenerator.generate(MessageGenerator.java:33)
    at net.redborder.utils.scheduler.StandardScheduler$SenderThread.run(StandardScheduler.java:69)
